### ISSUE TITLE
404 Not Found Error

### ISSUE THREAD

**Issue by ncrash** [quinvit/redmine_save_spent_time_queries#1]
Hi @quinvit 

Thank you so much to make this plugin.

I'm using bitnami redmine stack
redmine page url is "http://hostname:8080/redmine"

when onclick "Save" Button then showing 404 Not found error page.
fix please

have a good day!

**Comment by quinvit** [comment]
I've updated the code, use Redmine::Utils::relative_url_root.to_s instead of absolute url. Could you please have a try again?

**Comment by ncrash** [comment]
working fine :)
Thanks @quinvit 

But "Save spent time query" page when onclick "Save" Button then showing 500 Internal Server error..

And one more 404 error page..  => "Saved queries" button

best regard
daekwon.

**Comment by quinvit** [comment]
I've fixed 404 error, you could install plugin again to get it works. But I haven't found out 500 Internal Server error, could you please give me the log or the screenshot? Sorry I haven't tried Bitnami yet.

**Comment by ncrash** [comment]
Thanks for fastest feedback. :)

500 Internal Server error log

  Current user: dkkang@ucube.kr (id=36)
  Rendered common/error.html.erb within layouts/base (0.7ms)
  Rendered plugins/redmine_save_spent_time_queries/app/views/_spent_time_form.html.erb (2.2ms)
Redirected to
Completed 500 Internal Server Error in 37.0ms

AbstractController::DoubleRenderError (Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".):
  actionpack (3.2.16) lib/action_controller/metal/redirecting.rb:71:in `redirect_to'
  actionpack (3.2.16) lib/action_controller/metal/flash.rb:25:in`redirect_to'
  actionpack (3.2.16) lib/action_controller/metal/instrumentation.rb:60:in `block in redirect_to'
  activesupport (3.2.16) lib/active_support/notifications.rb:123:in`block in instrument'
  activesupport (3.2.16) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.16) lib/active_support/notifications.rb:123:in`instrument'
  actionpack (3.2.16) lib/action_controller/metal/instrumentation.rb:59:in `redirect_to'
  plugins/redmine_save_spent_time_queries/app/controllers/spent_time_query_controller.rb:67:in`save'
  actionpack (3.2.16) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.16) lib/abstract_controller/base.rb:167:in`process_action'
  actionpack (3.2.16) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.16) lib/abstract_controller/callbacks.rb:18:in`block in process_action'
  activesupport (3.2.16) lib/active_support/callbacks.rb:469:in `_run__2340299896262593195__process_action__385755248262832881__callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.16) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.16) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.16) lib/action_controller/metal/rescue.rb:29:in`process_action'
  actionpack (3.2.16) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.16) lib/active_support/notifications.rb:123:in`block in instrument'
  activesupport (3.2.16) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.16) lib/active_support/notifications.rb:123:in`instrument'
  actionpack (3.2.16) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.16) lib/action_controller/metal/params_wrapper.rb:207:in`process_action'
  activerecord (3.2.16) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.16) lib/abstract_controller/base.rb:121:in`process'
  actionpack (3.2.16) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.16) lib/action_controller/metal.rb:203:in`dispatch'
  actionpack (3.2.16) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.16) lib/action_controller/metal.rb:246:in`block in action'
  actionpack (3.2.16) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.16) lib/action_dispatch/routing/route_set.rb:73:in`dispatch'
  actionpack (3.2.16) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in`block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in`call'
  actionpack (3.2.16) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-openid (1.3.1) lib/rack/openid.rb:98:in`call'
  actionpack (3.2.16) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in`call'
  rack (1.4.5) lib/rack/conditionalget.rb:35:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/head.rb:14:in`call'
  actionpack (3.2.16) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/flash.rb:242:in`call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in`call'
  actionpack (3.2.16) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.16) lib/active_record/query_cache.rb:64:in`call'
  activerecord (3.2.16) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
  activesupport (3.2.16) lib/active_support/callbacks.rb:405:in `_run__171556961408781365__call__3963485663965927709__callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.16) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.16) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/remote_ip.rb:31:in`call'
  actionpack (3.2.16) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  railties (3.2.16) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.16) lib/rails/rack/logger.rb:16:in`block in call'
  activesupport (3.2.16) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.16) lib/rails/rack/logger.rb:16:in`call'
  actionpack (3.2.16) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in`call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.16) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/static.rb:63:in`call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:143:in`pass'
  rack-cache (1.2) lib/rack/cache/context.rb:155:in `invalidate'
  rack-cache (1.2) lib/rack/cache/context.rb:71:in`call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.16) lib/rails/engine.rb:484:in`call'
  railties (3.2.16) lib/rails/application.rb:231:in `call'
  railties (3.2.16) lib/rails/railtie/configurable.rb:30:in`method_missing'
  rack (1.4.5) lib/rack/builder.rb:134:in `call'
  rack (1.4.5) lib/rack/urlmap.rb:64:in`block in call'
  rack (1.4.5) lib/rack/urlmap.rb:49:in `each'
  rack (1.4.5) lib/rack/urlmap.rb:49:in`call'
  passenger (4.0.25) lib/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
  passenger (4.0.25) lib/phusion_passenger/request_handler/thread_handler.rb:140:in`accept_and_process_next_request'
  passenger (4.0.25) lib/phusion_passenger/request_handler/thread_handler.rb:108:in `main_loop'
  passenger (4.0.25) lib/phusion_passenger/request_handler.rb:441:in`block (3 levels) in start_threads'

**Comment by quinvit** [comment]
I think the bug has been fixed. Please try again.

**Comment by ncrash** [comment]
working fine save function.. but redirect action to 404 Page Not found error

please below log

  Current user: dkkang@ucube.kr (id=36)
Redirected to http://192.168.20.158:8080/redmine/spent_time_query
Completed 302 Found in 14.6ms (ActiveRecord: 6.9ms)
Started GET "/redmine/spent_time_query" for 192.168.20.192 at 2014-02-06 08:36:31 +0000
Processing by SpentTimeQueryController#index as HTML
  Current user: dkkang@ucube.kr (id=36)
  Rendered plugins/redmine_save_spent_time_queries/app/views/spent_time_query/index.html.erb within layouts/base (5.7ms)
Completed 500 Internal Server Error in 10.6ms

ActionController::RoutingError (No route matches {:controller=>"people", :action=>"show", :id=>36}):
  actionpack (3.2.16) lib/action_dispatch/routing/route_set.rb:540:in `raise_routing_error'
  actionpack (3.2.16) lib/action_dispatch/routing/route_set.rb:536:in`rescue in generate'
  actionpack (3.2.16) lib/action_dispatch/routing/route_set.rb:528:in `generate'
  actionpack (3.2.16) lib/action_dispatch/routing/route_set.rb:569:in`generate'
  actionpack (3.2.16) lib/action_dispatch/routing/route_set.rb:594:in `url_for'
  actionpack (3.2.16) lib/action_dispatch/routing/url_for.rb:148:in`url_for'
  actionpack (3.2.16) lib/action_view/helpers/url_helper.rb:107:in `url_for'
  actionpack (3.2.16) lib/action_view/helpers/url_helper.rb:242:in`link_to'
  plugins/redmine_save_spent_time_queries/app/views/spent_time_query/index.html.erb:26:in `block in _plugins_redmine_save_spent_time_queries_app_views_spent_time_query_index_html_erb___519322850781566241_64787240'
  activerecord (3.2.16) lib/active_record/relation/delegation.rb:6:in`each'
  activerecord (3.2.16) lib/active_record/relation/delegation.rb:6:in `each'
  plugins/redmine_save_spent_time_queries/app/views/spent_time_query/index.html.erb:15:in`_plugins_redmine_save_spent_time_queries_app_views_spent_time_query_index_html_erb___519322850781566241_64787240'
  actionpack (3.2.16) lib/action_view/template.rb:145:in `block in render'
  activesupport (3.2.16) lib/active_support/notifications.rb:125:in`instrument'
  actionpack (3.2.16) lib/action_view/template.rb:143:in `render'
  actionpack (3.2.16) lib/action_view/renderer/template_renderer.rb:47:in`block (2 levels) in render_template'
  actionpack (3.2.16) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (3.2.16) lib/active_support/notifications.rb:123:in`block in instrument'
  activesupport (3.2.16) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.16) lib/active_support/notifications.rb:123:in`instrument'
  actionpack (3.2.16) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionpack (3.2.16) lib/action_view/renderer/template_renderer.rb:46:in`block in render_template'
  actionpack (3.2.16) lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
  actionpack (3.2.16) lib/action_view/renderer/template_renderer.rb:45:in`render_template'
  actionpack (3.2.16) lib/action_view/renderer/template_renderer.rb:18:in `render'
  actionpack (3.2.16) lib/action_view/renderer/renderer.rb:36:in`render_template'
  actionpack (3.2.16) lib/action_view/renderer/renderer.rb:17:in `render'
  actionpack (3.2.16) lib/abstract_controller/rendering.rb:110:in`_render_template'
  actionpack (3.2.16) lib/action_controller/metal/streaming.rb:225:in `_render_template'
  actionpack (3.2.16) lib/abstract_controller/rendering.rb:103:in`render_to_body'
  actionpack (3.2.16) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
  actionpack (3.2.16) lib/action_controller/metal/compatibility.rb:50:in`render_to_body'
  actionpack (3.2.16) lib/abstract_controller/rendering.rb:88:in `render'
  actionpack (3.2.16) lib/action_controller/metal/rendering.rb:16:in`render'
  actionpack (3.2.16) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
  activesupport (3.2.16) lib/active_support/core_ext/benchmark.rb:5:in`block in ms'
  /ucube/redmine-2.4.2-0/ruby/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
  activesupport (3.2.16) lib/active_support/core_ext/benchmark.rb:5:in`ms'
  actionpack (3.2.16) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
  actionpack (3.2.16) lib/action_controller/metal/instrumentation.rb:83:in`cleanup_view_runtime'
  activerecord (3.2.16) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
  actionpack (3.2.16) lib/action_controller/metal/instrumentation.rb:39:in`render'
  actionpack (3.2.16) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (3.2.16) lib/action_controller/metal/implicit_render.rb:5:in`send_action'
  actionpack (3.2.16) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.16) lib/action_controller/metal/rendering.rb:10:in`process_action'
  actionpack (3.2.16) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.16) lib/active_support/callbacks.rb:469:in`_run__9221290126524426__process_action__3182444576103820810__callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.16) lib/active_support/callbacks.rb:385:in`_run_process_action_callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.16) lib/abstract_controller/callbacks.rb:17:in`process_action'
  actionpack (3.2.16) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.16) lib/action_controller/metal/instrumentation.rb:30:in`block in process_action'
  activesupport (3.2.16) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.16) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (3.2.16) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.16) lib/action_controller/metal/instrumentation.rb:29:in`process_action'
  actionpack (3.2.16) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.16) lib/active_record/railties/controller_runtime.rb:18:in`process_action'
  actionpack (3.2.16) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.16) lib/abstract_controller/rendering.rb:45:in`process'
  actionpack (3.2.16) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.16) lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
  actionpack (3.2.16) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.16) lib/action_dispatch/routing/route_set.rb:73:in`call'
  actionpack (3.2.16) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.16) lib/action_dispatch/routing/route_set.rb:36:in`call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in`each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.16) lib/action_dispatch/routing/route_set.rb:608:in`call'
  rack-openid (1.3.1) lib/rack/openid.rb:98:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in`call'
  actionpack (3.2.16) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
  actionpack (3.2.16) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in`context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/cookies.rb:341:in`call'
  activerecord (3.2.16) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.16) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in`call'
  actionpack (3.2.16) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.16) lib/active_support/callbacks.rb:405:in`_run__4272883092310299217__call__1683717125470255965__callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.16) lib/active_support/callbacks.rb:385:in`_run_call_callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.16) lib/action_dispatch/middleware/callbacks.rb:27:in`call'
  actionpack (3.2.16) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/debug_exceptions.rb:16:in`call'
  actionpack (3.2.16) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.16) lib/rails/rack/logger.rb:32:in`call_app'
  railties (3.2.16) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.16) lib/active_support/tagged_logging.rb:22:in`tagged'
  railties (3.2.16) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/request_id.rb:22:in`call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in`call'
  activesupport (3.2.16) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in`call'
  actionpack (3.2.16) lib/action_dispatch/middleware/static.rb:63:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in`forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in`lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in`call'
  railties (3.2.16) lib/rails/engine.rb:484:in `call'
  railties (3.2.16) lib/rails/application.rb:231:in`call'
  railties (3.2.16) lib/rails/railtie/configurable.rb:30:in `method_missing'
  rack (1.4.5) lib/rack/builder.rb:134:in`call'
  rack (1.4.5) lib/rack/urlmap.rb:64:in `block in call'
  rack (1.4.5) lib/rack/urlmap.rb:49:in`each'
  rack (1.4.5) lib/rack/urlmap.rb:49:in `call'
  passenger (4.0.25) lib/phusion_passenger/rack/thread_handler_extension.rb:77:in`process_request'
  passenger (4.0.25) lib/phusion_passenger/request_handler/thread_handler.rb:140:in `accept_and_process_next_request'
  passenger (4.0.25) lib/phusion_passenger/request_handler/thread_handler.rb:108:in`main_loop'
  passenger (4.0.25) lib/phusion_passenger/request_handler.rb:441:in `block (3 levels) in start_threads'

**Comment by ncrash** [comment]
r u invisible "Saved queries" button?

please restore "Saved queries"  function

**Comment by quinvit** [comment]
Fixed again he he! This is my first plugin for Redmine and you are the first user!

**Comment by ncrash** [comment]
Working Fine All

Thank you so much.
I'm glad to first user :)

I'd appreciate use this plugin 

have a nice day!
